# Generated by Django 6.0a1 on 2026-07-13 07:42

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('codename', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('long_description', models.TextField()),
                ('live_link', models.CharField(blank=True, max_length=255)),
                ('repo_link', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='projects/', validators=[projects.validators.validate_image_file])),
                ('category', models.CharField(max_length=100)),
                ('tech_stack', models.JSONField()),
                ('highlights', models.JSONField()),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
