# Generated by Django 6.0a1 on 2026-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_seed_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_p1', models.TextField()),
                ('bio_p2', models.TextField()),
                ('stack', models.CharField(default='MERN', max_length=100)),
                ('focus', models.CharField(default='Full Stack', max_length=100)),
                ('approach', models.CharField(default='System Design', max_length=100)),
                ('status', models.CharField(default='Active', max_length=100)),
                ('owner_email', models.EmailField(default='goyalaniket2006@gmail.com', max_length=254)),
                ('default_from_email', models.EmailField(default='goyalaniket2006@gmail.com', max_length=254)),
            ],
        ),
    ]
