# Generated by Django 6.0a1 on 2026-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_seed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('issuer', models.CharField(max_length=200)),
                ('status', models.CharField(default='UNLOCKED', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('contributions', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='Aniket', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_label',
            field=models.CharField(default='github.com/aniketgoyal12', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.CharField(default='https://github.com/aniketgoyal12', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_subtitle',
            field=models.CharField(default='Full Stack Developer · Systems Engineer', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_title_p1',
            field=models.CharField(default="I don't just build projects. ", max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_title_p2',
            field=models.CharField(default='I engineer systems.', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Goyal', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_label',
            field=models.CharField(default='linkedin.com/in/aniketgoyal-ag/', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(default='https://linkedin.com/in/aniketgoyal-ag/', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='logo_initials',
            field=models.CharField(default='AG', max_length=10),
        ),
    ]
