# Generated by Django 6.0a1 on 2026-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_seed_portfolio_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='approach',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='focus',
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(default='Open to internships', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(default='Full Stack — 1 yr projects', max_length=100),
        ),
    ]
