# Generated by Django 6.0a1 on 2026-07-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
